name: Build
on: [push]
jobs:
  build:
   name: share
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - run: docker build . -t onionshare
    - run: |
        nohup docker run -t -v $PWD/shared:/shared onionshare &
        sleep 1m
        cat nohup.out
    - run: if grep on .github/ngrok ; then bash .github/debug-github-actions.sh ; fi
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.NGROK_PASSWORD }}
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
    - run: sleep 5h
